### ISSUE TITLE
Text Shadow Disappears and Sponsor Logo Misaligns After Multiple Menu Clicks

### ISSUE THREAD

**Issue by solotov-val** [BombastischeBouncingBuggyBuilderBande/GolfCar#37]
## Description
After interacting with the menu items, specifically after opening and closing a menu item twice, the text shadow is no longer visible. Additionally, the sponsor logo becomes misaligned after these interactions.

![nixsolecker](https://github.com/BombastischeBouncingBuggyBuilderBande/GolfCar/assets/104975754/323d81f2-dc6d-436c-88a1-4f86282e2589)

## Steps to Reproduce
1. Click on any menu item to open it.
2. Click again to close it.
3. Repeat steps 1 and 2 once more.
4. Observe that the text shadow has disappeared and the sponsor logo is misaligned.

## Expected Behavior
The text shadow should remain consistent after multiple interactions, and the sponsor logo should retain its proper alignment.

## Actual Behavior
The text shadow vanishes and the sponsor logo is misaligned after the menu has been opened and closed twice.

**Comment by solotov-val** [comment]
@Quaenshot @alexpede21

**Comment by Quaenshot** [comment]
fixed
